#!/bin/bash
# Convert SVGs to PDFs.
# Usage: convert /target/dir
echo "Converting SVGs..."
cd $@
for i in *.svg; do
  filename=$(basename "$i")
  filename="${filename%.*}"
  echo "${filename}"
  inkscape -A "$filename.pdf" "$filename.svg"
done

# Mergre PDFs.
echo "Merging PDFs..."
pdfunite *.pdf "$@.pdf"
