#!/bin/ruby
require 'active_support/inflector'

@data = Hash.new
@file = 'data.csv'

# Interperet terminal commands.
def interperet
	cmd = ARGV[0]
	case (cmd)
		when '-b' then build
		when '-c' then create
		when '--clean' then clean
		when '--help' then help
		when '-r' then run
		else puts "Command: \"#{cmd}\" is unrecognized."
	end
end

# Build an image from dockerfile.
def build
	image_name = ARGV[1]
	docker_file_path = ARGV[2]

	cmd = "docker build --rm=true -t #{image_name} #{docker_file_path}"
	puts "Building image..."
	puts cmd
	`#{cmd}`
end

# Clean all docker containers.
def clean
 puts "Cleaning herds..."
 File.open(@file, 'w') {}
 exec("docker rm `docker ps --no-trunc -aq`")
end

# Instantiate a herd of docker containers.
def create
	image = ARGV[1]
	n = ARGV[2].to_i
	herd_name = image.pluralize
	args = "docker create"
	commit(herd_name, n)

	puts "Creating herd..."
	(1..n).each do |d|
		cmd = args + " --name #{image}#{d} #{image}"
		puts cmd
		`#{cmd}`
	end
end

# Run a command against the herd.
def run
	herd_name = ARGV[1]
	cmd = "docker " << ARGV[2]
	args = ARGV.drop(3).join(" ")
	n = @data[herd_name].to_i

	(1..n).each do |d|
		puts "#{cmd} #{herd_name}#{d} #{args}"
		`#{cmd} #{herd_name}#{d} #{args}`
	end
end

# Write a value to data file for storage.
def commit(key, value)
	File.open(@file, 'a') { puts "#{key}, #{value}" }
end

# Load herd data from file.
def load_data
	File.open(@file, 'r').each_line do |line|
		tokens = line.split(",")
		@data[tokens[0]] = tokens[1]
		puts "Loaded herd: #{tokens[0]}, size: #{tokens[1]}"
	end if File.exists?(@file)
end

# Print help commands.
def help
	puts "Build a Dockerfile:"
	puts "  herder -b <image_name> <path_to_dockerfile>"
	puts ""
	puts "Clean all Docker containers:"
	puts "  herder --clean"
	puts ""
	puts "Create a new herd:"
	puts "  herder -c <image_name> <count>"
	puts ""
	puts "Run command over a herd:"
  puts "  herder -r <herd_name> <docker_command>"
end


# Run the script.
load_data
puts "
 ___________
 < Herder >
 -----------
       \\   ^__^
        \\  (oo)\\_______
           (__)\\       )\\/\\
                ||----w |
                ||     ||"
interperet
